# Generated by Django 4.2.1 on 2023-09-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('limit_bal', models.IntegerField()),
                ('sex', models.PositiveSmallIntegerField()),
                ('education', models.PositiveSmallIntegerField()),
                ('marriage', models.PositiveSmallIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('pay_0', models.IntegerField()),
                ('pay_2', models.IntegerField()),
                ('pay_3', models.IntegerField()),
                ('pay_4', models.IntegerField()),
                ('pay_5', models.IntegerField()),
                ('pay_6', models.IntegerField()),
                ('bill_amt1', models.IntegerField()),
                ('bill_amt2', models.IntegerField()),
                ('bill_amt3', models.IntegerField()),
                ('bill_amt4', models.IntegerField()),
                ('bill_amt5', models.IntegerField()),
                ('bill_amt6', models.IntegerField()),
                ('pay_amt1', models.IntegerField()),
                ('pay_amt2', models.IntegerField()),
                ('pay_amt3', models.IntegerField()),
                ('pay_amt4', models.IntegerField()),
                ('pay_amt5', models.IntegerField()),
                ('pay_amt6', models.IntegerField()),
                ('default_payment_next_month', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=4, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insights', models.JSONField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
